# Generated by Django 2.2.4 on 2019-12-24 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab4d9824-2604-11ea-a85d-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
