# Generated by Django 2.2.4 on 2019-12-24 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191224_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ccc1688-260d-11ea-a2d7-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
