# Generated by Django 2.2.4 on 2019-12-24 05:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191224_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('rfid', models.CharField(default='', max_length=25)),
                ('amount', models.CharField(default='0', max_length=10)),
                ('slot_number', models.CharField(default='', max_length=5, verbose_name='slot number')),
                ('location', models.CharField(default='', max_length=50)),
                ('user_id', models.CharField(default='', max_length=75, verbose_name='user id')),
                ('razorpay_order_id', models.CharField(default='', max_length=75, verbose_name='razorpay order id')),
                ('razorpay_payment_id', models.CharField(default='', max_length=75, verbose_name='razorpay payment id')),
                ('razorpay_signature', models.CharField(default='', max_length=75, verbose_name='razorpay signature')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2748e612-260d-11ea-b27a-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
