# Generated by Django 2.2.4 on 2019-12-24 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191224_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4acbf39e-2612-11ea-9413-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
