# Generated by Django 2.2.4 on 2019-12-24 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191224_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cdd6d230-2664-11ea-9580-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
