# Generated by Django 2.2.4 on 2019-12-24 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191224_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e05eeea8-266e-11ea-9060-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
