# Generated by Django 2.2.4 on 2020-03-14 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191224_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('428a7f78-660a-11ea-939d-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
