# Generated by Django 2.2.4 on 2020-03-14 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200314_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bfffbada-660b-11ea-a2c6-54bf644e2c92'), primary_key=True, serialize=False),
        ),
    ]
